UPDATE service_calls
SET start_time = $1,
    end_time = $2,
    user_id = $3,
    salt = $4,
    phosphates = $5,
    tds = $6,
    filter_psi = $7,
    chlorine = $8,
    ph = $9,
    alkalinity = $10,
    cya = $11,
    trichlor_shock = $12,
    soda_ash = $13,
    sodium_bicarbonate = $14,
    tabs = $15,
    granular_trichlor = $16,
    phosphate_remover = $17,
    muriatic_acid = $18,
    sodium_thiosulfate = $19,
    stabilizer = $20,
    green_to_clean = $21,
    de = $22,
    service_address_id = $23,
WHERE id = $24;

RETURNING id, start_time AS startTime, end_time AS endTime, user_id AS userId, salt, phosphates, tds, filter_psi AS filterPsi, chlorine, ph, alkalinity, cya, trichlor_shock AS trichlorShock, soda_ash AS sodaAsh, sodium_bicarbonate AS sodiumBicarbonate, tabs, granular_trichlor AS granularTrichlor, phosphate_remover AS phosphateRemover, muriatic_acid AS muriaticAcid, sodium_thiosulfate AS sodiumThiosulfate, stabilizer, green_to_clean AS greenToClean, de, service_address_id AS serviceAddressId;